FROM nemo_base:latest

ENV FLASK_ENV=development

WORKDIR /var/nemo

# Add development dependencies
COPY requirements.dev.txt ./
RUN pip3 install -r requirements.dev.txt

# Install application module
RUN python3 setup.py develop

# Copy bootstrap script
WORKDIR /var/nemo
COPY bin/bootstrap.dev.sh ./bin/bootstrap.dev.sh

# Application is served on port 5000
EXPOSE 5000
# webpack-dev-server uses port 5001 for live reload
EXPOSE 5001

CMD /var/nemo/bin/bootstrap.dev.sh
